config/routes.rb
Juconsulting::Application.routes.draw do
  resources :consults

  get "tools/index"
  get "education/index"
  root "home#index"
  get "company/index"
  get "company/intro"
  get "company/partner"
  get "about_us/index"
  get "about_us/choisw"
  get "about_us/kimjh"
  get "about_us/organization"
  get "about_us/consultant"
  get "about_us/perf"
  get "home/index"
  get "courses/manager_index"
  get "courses/manager_show"
  get "consulting/manager_index"
  get "consults/manager_index"

  resources :courses do
    resource :course_programs
  end

  resources :consulting

end

app/models/consult.rb
class Consult < ActiveRecord::Base
end

app/models/consulting.rb
class Consulting < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :course_programs, dependent: :destroy
end

app/models/course_program.rb
class CourseProgram < ActiveRecord::Base
	belongs_to :course
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index
  end

  def choisw
  end

  def kimjh
  end

  def organization
  end

  def consultant
  end

  def perf
  end
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  def index
  end
  def intro
  end
  def perf
  end
  def partner
  end
end

app/controllers/consulting_controller.rb
class ConsultingController < ApplicationController
  before_action :call_consulting

  def call_consulting
    @consultings = Consulting.all
  end

  def index
  end

  def new
	@consulting = Consulting.new
  end
  def create
	@consulting = Consulting.new(consulting_params)
	if @consulting.save
		redirect_to controller: "consultings", action:"manager_index"
	else
		render 'new'
	end
  end
  def manager_index
	@consultings = Consulting.all
  end

  def show
    @consulting = Consulting.find(params[:id])
  end
  private
	def consulting_params
		params.require(:consulting).permit(:title, :banner_txt, :desc, :features, :main_img, :etc_img)
	end
end

app/controllers/consults_controller.rb
class ConsultsController < ApplicationController
  before_action :set_consult, only: [:show, :edit, :update, :destroy]

  # GET /consults
  # GET /consults.json
  def index
    @consults = Consult.all
  end

  # GET /consults/1
  # GET /consults/1.json
  def show
    @consults = Consult.all
  end

  # GET /consults/new
  def new
    @consult = Consult.new
  end

  # GET /consults/1/edit
  def edit
  end

  # POST /consults
  # POST /consults.json
  def create
    @consult = Consult.new(consult_params)

    respond_to do |format|
      if @consult.save
        format.html { redirect_to @consult, notice: 'Consult was successfully created.' }
        format.json { render action: 'show', status: :created, location: @consult }
      else
        format.html { render action: 'new' }
        format.json { render json: @consult.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consults/1
  # PATCH/PUT /consults/1.json
  def update
    respond_to do |format|
      if @consult.update(consult_params)
        format.html { redirect_to @consult, notice: 'Consult was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @consult.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consults/1
  # DELETE /consults/1.json
  def destroy
    @consult.destroy
    respond_to do |format|
      format.html { redirect_to consults_url }
      format.json { head :no_content }
    end
  end

  def manager_index
	render 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consult
      @consult = Consult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consult_params
      params[:consult]
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
	@courses = Course.all
  end
  def manager_index
	@courses = Course.all
  end
  def edit
	@course = Course.find(params[:id])
  end
  def update
	@course = Course.find(params[:id])
	if @course.update(course_params)
		redirect_to @course
	else
		render 'edit'
	end
  end

  def show
	@courses = Course.all
	@course = Course.find(params[:id])
  end
  def manager_show
	@course = Course.find(params[:id])
  end
  def new
	@course = Course.new
  end
  def create
	@course = Course.new(course_params)
	if @course.save
		redirect_to controller: "courses", action:"manager_show", id: @course.id
	else
		render 'new'
	end
  end

  def destroy
	@course = Course.find(params[:id])
	@course.destroy

	redirect_to controller: "courses", action:"manager_index"
  end

  private
	def course_params
		params.require(:course).permit(:title, :purpose, :feature, :overview_number_of_memeber, :overview_type, :overview_target, :overview_time, :expectation)
	end
end

app/controllers/education_controller.rb
class EducationController < ApplicationController
  def index
	@courses = Course.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/consulting_helper.rb
module ConsultingHelper
end

app/helpers/consults_helper.rb
module ConsultsHelper
end

app/helpers/course_programs_helper.rb
module CourseProgramsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/education_helper.rb
module EducationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/about_us/_banner.html.erb
<span>About Us</span>

app/views/about_us/_sidemenu.html.erb
<ul class="global-child">
  <li><%= link_to "회사 소개 및 일반 현황", "#" %></li>
  <li><%= link_to "회사 사업 실적", about_us_perf_path %></li>
  <li><a href="/about_us/consultant">컨설턴트 소개</a></li>
  <li><a href="#">조직도</a></li>
  <li><a href="#">고객사</a></li>
</ul>

app/views/about_us/choisw.html.erb
<h2>최성운 대표</h3>
<h3>Chief  Architect</h3>
<h3>인적사항</h3>
<ul>
  <li>명지대학교 컴퓨터공학부 교수</li>
  <li>OMG Korea 회장</li>
  <li>미국 오레곤 주립대학 (공학박사), 1992년,</li>
</ul>
<h3>연구 분야</h3>
<ul>
  <li>아키텍처 기반 시스템 개발 (Architecture-Centric System Development)</li>
  <li>서비스 기반 아키텍처 (Service-Oriented Architecture)</li>
  <li>소프트웨어 개발 프로세스 (Software Development Process)</li>
</ul>
<h3>주요 경력</h3>
<ul>
  <li>2013.08 ~ 현재: 삼성 테크윈 아키텍트 양성 강사 및 심사위원</li>
  <li>2013.06 ~ 현재: 현대엠엔소프트 컨설팅 -차세대 네비게이션 플랫폼 아키텍처</li>
  <li>2011.01-2012.12: 투비소프트 기술자문-차세대 Xplatform 아키텍처</li>
  <li>2008.01-2009.12: 삼성SDS 기술자문-메타프로세스 기반 프로세스 통합</li>
  <li>2007.01-2007.06: 삼성SDS 기술자문-개발/관리/감리 방법론</li>
  <li>2006.02-2006.09: 삼성전자 기술자문-차세대 Mobile Phone을 위한 미들웨어 아키텍처</li>
  <li>2006.02-2006.09: 이바야콥슨컨설팅 기술자문-Aspect-Oriented 방법론</li>
</ul>

app/views/about_us/consultant.html.erb
<section class="about-us-subpage">
  <h3 id="consultant-title">컨설턴트 소개</h3>
  <div class="consultant">
    <h3 class="consultant-name">최성운 교수 (고문)</h3>
    <p class="consultant-role">Chief Architect</p>
    <table class="consultant-desc">
      <tr>
        <th>인적사항</th>
        <td>
          <p>명지대학교 컴퓨터공학부 교수</p>
          <p>OMG Korea 회장</p>
          <p>미국 오레곤 주립대학(공학박사), 1992년,</p>
        </td>
      </tr>
      <tr>
        <th>연구분야</th>
        <td>
          <p>아키텍처 기반 시스템 개발 (Architecture-Centric System Development</p>
          <p>서비스 기반 아키텍처 (Service-Oriented Architecture)</p>
          <p>소프트웨어 개발 프로세스 (Software Development Process</p>
        </td>
      </tr>
      <tr>
        <th>주요경력</th>
        <td>
          <p>2013.08 ~ 현재: 삼성 테크윈 아키텍트 양성 강사 및 심의위원</p>
          <p>2013.06 ~ 현재: 현대엠앤소프트 컨설팅 - 차세대 네비게이션 플랫폼 아키텍처</p>
          <p>2011.01 ~ 2012.12: 투비소프트 기술자문 - 차세대 Xplatform 아키텍처</p>
          <p>2008.01 ~ 2009.12: 삼성SDS 기술자문 - 메타프로세스 기반 프로세스 통합</p>
          <p>2007.01 ~ 2007.07: 삼성SDS 기술자문 - 개발/관리/감리 방법론</p>
          <p>2006.02 ~ 2006.09: 삼성전자 기술자문 - 차세대 Mobile Phone을 위한 미들웨어 아키텍처</p>
          <p>2006.02 ~ 2006.09: 이바야콥슨컨설팅 기술자문 - Aspected-Oriented 방법론</p>

        </td>
      </tr>
    </table>
  </div>
  <div class="consultant">
    <h3 class="consultant-name">김정호 대표</h3>
    <p class="consultant-role">Senior Architect</p>
    <table class="consultant-desc">
      <tr>
        <th>인적사항</th>
        <td>
          <p>(주) 제이유컨설팅 대표이사</p>
          <p>NIPA 소프트웨어 전문위원</p>
          <p>Carnegie Mellon University: Master - Software Engineering 전공</p>
          <p>KAIST: Ph.D 수료 - Software Architecture 전공</p>
        </td>
      </tr>
      <tr>
        <th>연구분야</th>
        <td>
          <p>소프트웨어 아키텍처 이론과 실제 (에이콘 2007, 번역)</p>
          <p>소프트웨어 아키텍처 문서화 (에이콘 2008, 번역)</p>
          <p>Software architecture reconstruction for extensibility (KCSE 2009, 논문)</p>
          <p>The method for verifying software architecture with FSP model (ICACT 2010, 논문)</p>
          <p>엔터프라이즈 애플리케이션을 위한 소프트웨어 아키텍처 개발 실무 (KOSTA, 2010, 저술)</p>
        </td>
      </tr>
      <tr>
        <th>주요경력</th>
        <td>
          <p>2011.06 ~ 현재: 삼성 테크윈 아키텍트 양성과정 - 아키텍트 양성 강사 및 멘토</p>
          <p>2013.06 ~ 현재: 현대엠엔소프트웨어 네비게이션 플랫폼 - 아키텍처 설계 컨설턴트</p>
          <p>2006.09 ~ 2007.03: 한화손해보험 차세대 시스템 - 소프트웨어 아키텍트</p>
          <p>2007.03 ~ 2008.01: 대신증권 차세대 시스템 - 소프트웨어 아키텍트</p>
          <p>2008.01 ~ 2010.06: SK 가상세계 서비스 플랫폼 - 소프트웨어 아키텍트</p>
        </td>
      </tr>
    </table>
  </div>
  

</section>

app/views/about_us/index.html.erb
<h1>AboutUs#index</h1>
<p>Find me in app/views/about_us/index.html.erb</p>

app/views/about_us/kimjh.html.erb
<h2>김정호 대표</h2>
<h3>Senior Architect</h3>

<h3>인적사항</h3>
<ul>
<li>㈜제이유컨설팅 대표이사</li>
<li>NIPA 소프트웨어 전문위원</li>
<li>Carnegie Mellon University: Master - Software Engineering 전공</li>
<li>KAIST: Ph.D 수료 - Software Architecture 전공</li>
</ul>
<h3>저술</h3>
<ul>
<li>소프트웨어 아키텍처 이론과 실제 (에이콘 2007, 번역)</li>
<li>소프트웨어 아키텍처 문서화 (에이콘 2008, 번역)</li>
<li>Software architecture reconstruction for extensibility (KCSE 2009, 논문)</li>
<li>The method for verifying software architecture with FSP model (ICACT 2010, 논문)</li>
<li>엔터프라이즈 애플리케이션을 위한 소프트웨어 아키텍처 개발 실무 (KOSTA, 2010, 저술)</li>
</ul>
<h3>주요 경력</h3>
<ul>
<li>2011.06 ~ 현재: 삼성 테크윈 아키텍트 양성 과정– 아키텍트 양성 강사 및 멘토</li>
<li>2013.06 ~ 현재: 현대엠엔소프트 네비게이션 플랫폼 – 아키텍처 설계 컨설턴트</li>
<li>2006.09 ~ 2007.03: 한화손해보험 차세대 시스템 - 소프트웨어 아키텍트</li>
<li>2007.03 ~ 2008.01: 대신증권 차세대 시스템 - 소프트웨어 아키텍트</li>
<li>2008.01 ~ 2010.06:  SK 가상세계 서비스 플랫폼 - 소프트웨어 아키텍트</li>
</ul>

app/views/about_us/perf.html.erb
<section class="about-us-subpage">
  <h3>회사 사업 실적</h3>
  
  <table class="ju-table">
    <thead>
      <tr>
        <th>사업명</th>
        <th>사업기간</th>
        <th>발주처</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          현대자동차<br />
          소프트웨어 아키텍처 설계 교육
        </td>
        <td>2011.07~2011.08</td>
        <td>현대자동차</td>
      </tr>
      <tr>
        <td>현대 모비스 아키텍트 양성 교육</td>
        <td>2011.10 ~ 2012.03</td>
        <td>현대모비스</td>
      </tr>
      <tr>
        <td>삼성전자 아키텍트 양성 교육 </td>
        <td>2013.04 ~ 2013.05</td>
        <td>삼성전자</td>
      </tr>
      <tr>
        <td>소프트웨어 아키텍처 설계 교육</td>
        <td>2013.05 ~ 2013.11</td>
        <td>전자통신연구원(ETRI)</td>
      </tr>
      <tr>
        <td>WBS 1, 2차  분석/설계 점검 및 멘토링</td>
        <td>2010.12 ~ 2013.06</td>
        <td>NIPA</td>
      </tr>
      <tr>
        <td>삼성 테크윈 아키텍트 양성 멘토링</td>
        <td>2010.10 ~ 현재</td>
        <td>삼성테크윈</td>
      </tr>
      <tr>
        <td>
          소프트웨어 프로덕트 라인<br />
          프레임워크 설계 및 구현
        </td>
        <td>2013.06 ~ 2014.06</td>
        <td>현대엠엔소프트</td>
      </tr>
    </tbody>
  </table>
<section>

app/views/company/_banner.html.erb
<span>Company</span>

app/views/company/_sidemenu.html.erb
<ul>
  <li><%= link_to "회사 소개", company_intro_path %></li>
  <li><%= link_to "사업 실적", company_perf_path %></li>
  <li><%= link_to "고객사", company_partner_path %></li>
</ul>

app/views/company/index.html.erb
<h1>회사 소개</h1>

app/views/company/intro.html.erb
<p>제이유 컨설팅은 지난 3년간 현대자동차, 현대모비스, 삼성전자, 삼성테크윈, 한국전자통신연구원(ETRI) 등 국내 최고의 소프트웨어 개발 업체의 아키텍트 양성 강의 및 멘토링을 담당하며 아키텍트 양성을 주도하였다. 또한 대형 국책 과제인 World Best Software(WBS)의  자동차 플랫폼, 무인 항공기 소프트웨어 개발에서 분석/설계 점검 및 멘토링을 진행하였다. 이를 응용하여 현대엠엔소프트에서 내비게이션 제품을 위한 프로덕트 라인 기반의 프레임워크를 분석/설계 컨설팅을 진행하였다.</p>
<table>
  <tr>
    <td colspan=2 rowspan=3>업체명</td>
    <td rowspan=3>JU Consulting</td>
    <td colspan=4>최근 3년간 기업현황(단위: 천원, 명)</td>
  </tr>
  <tr>
    <td>구분</td>
    <td>2011</td>
    <td>2012</td>
    <td>2013</td>
  </tr>
  <tr>
    <td>총자산</td>
    <td>7,626</td>
    <td>3,212</td>
    <td>47,926</td>
  </tr>
  <tr>
    <td colspan=2>설 립 년 월 일</td>
    <td>2011년 6월 4일</td>
    <td>총자본</td>
    <td>-14,800</td>
    <td>-603</td>
    <td>16,330</td>
  </tr>
  <tr>
    <td colspan=2>사업자등록번호</td>
    <td>314-86-24768</td>
    <td>총부채</td>
    <td>22,427</td>
    <td>3,815</td>
    <td>31,595</td>
  </tr>
  <tr>
    <td colspan=2>법인등록번호</td>
    <td></td>
    <td>매출액</td>
    <td>16,363</td>
    <td>78,950</td>
    <td>109,387</td>
  </tr>
  <tr>
    <td colspan=2>대표자성명</td>
    <td>정진성</td>
    <td>총인원</td>
    <td>1</td>
    <td>2</td>
    <td>3</td>
  </tr>
  <tr>
    <td rowspan=2>주소</td>
    <td>본사</td>
    <td>대전 유성구 어은동</td>
    <td rowspan=2>연락처</td>
    <td>전화</td>
    <td colspan=2>010-5386-8986</td>
  </tr>
  <tr>
    <td>홈페이지</td>
    <td></td>
    <td>팩스</td>
    <td colspan=2>042-328-8986</td>
  </tr>
  <tr>
    <td colspan=2>조직규모</td>
    <td colspan=6>총(3)명, 컨설팅인력(2)명</td>
  </tr>

</table>

app/views/courses/_sidemenu.html.erb
<ul class="global-child">
  <% Course.all.each do |course| %>
    <li><%= link_to course.title, course_path(course) %></li>
  <% end %>
</ul>

app/views/courses/edit.html.erb
<%= form_for :course, url: course_path(@course), method: :patch  do |f| %>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <title>Edit Course description</title>
    <style>
      table {
        width: 800px;
		height: 500px;
      }
      table{
        border-style: solid;
		border-width: 2px;
		border-collapse: collapse;
      }
	  th, td{
        border-style: solid;
		border-width: 1px;
      }
	  th{
		background-color: gray;
	  }
	  th.col1{
		width: 100px;
	  }
	  th.col2, td.col2{
		width: 150px;
	  }
	  th.col3, td.col3{
		width: 40px;
	  }
	  th.col4, td.col4{
		width: 60px;
	  }
    </style>
  </head>
  <body>
    <table>
      <thead>
        <tr>
          <th class = "col1">과목명</th>
          <th colspan= "6"><%= f.text_field:title %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th class = "col1">과정목표</th>
          <td  colspan= "6"><%= f.text_area:purpose %></td>
          <!-- <td rowspan="2">Dolor</td> -->
        </tr>
        <tr>
          <th class = "col1">과목특징</th>
          <td  colspan= "6"><%= f.text_area:feature %></td>
        </tr>
        <tr>
          <th rowspan="2", class = "col1">과정개요</th>
          <th class = "col2">교육인원</th>
          <td><%= f.number_field :overview_number_of_member ,in: 1..100 ,step: 1 %></td>
          <th class = "col2">교육형태</th>
	  <td colspan= "2"><%= f.text_field :overview_type %></td>
        </tr>
	<tr>
          <th class = "col2">교육대상</th>
          <td><%= f.text_area :overview_target %></td>
          <th class = "col2">교육시간</th>
	  <td colspan= "2"><%= f.text_field :overview_time%></td>
        </tr>
	<tr>
	  <th>프로그램</th>
          <th class = "col2">LO</th>
          <th colspan= "2">교육내용</th>
          <th class = "col3">교육시간</th>
		  <th class = "col4">비고</th>
        </tr>
        <th class = "col1">기대효과</th>
	  <td colspan= "6"><%= f.text_area :expectation %></td>
        </tr>
      </tbody>
    </table>
    <p>
	<%= f.submit %>
    <p>
  </body>
</html>
<% end %>

app/views/courses/index.html.erb
<h1>Education#index</h1>
<p>Find me in app/views/education/index.html.erb</p>

<p> Course List </p>
<table>
 <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= link_to 'Show', course_path(course) %></td>
      </tr>
 <% end %>
</table>

app/views/courses/manager_index.html.erb
<h1>Education#index</h1>
<p>Find me in app/views/education/index.html.erb</p>

<p><%= link_to 'Regist course', controller:"courses", action: "new" %></p>
<p> Course List </p>
<table>
 <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= link_to 'Add program', controller:"courses", action: "manager_show", id:course %></td>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course_path(course),
				method: :delete,
				data: {confirm: 'Are you sure?' }  %></td>
      </tr>
 <% end %>
</table>

app/views/courses/manager_show.html.erb
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <title>Manager Course description</title>
  </head>
  <body>
    <table>
      <thead>
        <tr>
          <th class = "col1">과목명</th>
          <th colspan= "7"><%= @course.title %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th class = "col1">과정목표</th>
          <td  colspan= "7"><%= @course.purpose %></td>
          <!-- <td rowspan="2">Dolor</td> -->
        </tr>
        <tr>
          <th class = "col1">과목특징</th>
          <td  colspan= "7"><%= @course.feature %></td>
        </tr>
        <tr>
          <th rowspan="2", class = "col1">과정개요</th>
          <th class = "col2">교육인원</th>
          <td colspan= "2"><%= @course.overview_number_of_member %>명 내외</td>
          <th class = "col2">교육형태</th>
	  <td colspan= "2"><%= @course.overview_type %></td>
        </tr>
		<tr>
          <th class = "col2">교육대상</th>
          <td colspan = "2"><%= @course.overview_target %></td>
          <th class = "col2">교육시간</th>
	  <td colspan= "2"><%= @course.overview_time%></td>
        </tr>
	<tr>
	  <th rowspan= <%= @course.course_programs.size + 2 %>, class = "col1"> 프로그램</th>
          <th class = "col2">LO</th>
          <th colspan= "2">교육내용</th>
          <th class = "col3">교육시간</th>
	  <th colspan= "2", class = "col4">비고</th>
        </tr>

	<%= render @course.course_programs %>
	<%= form_for([@course,@course.course_programs.build]) do |f2| %>
 	<tr>
          <td class = "col2"><%= f2.text_field :lo %></td>
          <td colspan= "2"><%= f2.text_area :contents %></td>
          <td class = "col3"><%= f2.number_field :time, in: 1..20, step: 0.5  %></td>
	  <td class = "col4"><%= f2.text_area :note %></td>
          <td>
	<%= f2.submit %>
	  </td>
        </tr>
	<% end %>
          <th class = "col1">기대효과</th>
	  <td colspan= "7"><%= @course.expectation %></td>
        </tr>
      </tbody>
    </table>
  </body>
</html>

app/views/courses/new.html.erb
<%= form_for :course, url: courses_path do |f| %>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <title>Course description</title>
  </head>
  <body>
    <table>
      <thead>
        <tr>
          <th class = "col1">과목명</th>
          <th colspan= "6"><%= f.text_field:title %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th class = "col1">과정목표</th>
          <td  colspan= "6"><%= f.text_area:purpose %></td>
          <!-- <td rowspan="2">Dolor</td> -->
        </tr>
        <tr>
          <th class = "col1">과목특징</th>
          <td  colspan= "6"><%= f.text_area:feature %></td>
        </tr>
        <tr>
          <th rowspan="2", class = "col1">과정개요</th>
          <th class = "col2">교육인원</th>
          <td><%= f.number_field :overview_number_of_member ,in: 1..100 ,step: 1 %></td>
          <th class = "col2">교육형태</th>
	  <td colspan= "2"><%= f.text_field :overview_type %></td>
        </tr>
	<tr>
          <th class = "col2">교육대상</th>
          <td><%= f.text_area :overview_target %></td>
          <th class = "col2">교육시간</th>
	  <td colspan= "2"><%= f.text_field :overview_time %></td>
        </tr>
	<tr>
	  <th>프로그램</th>
          <th class = "col2">LO</th>
          <th colspan= "2">교육내용</th>
          <th class = "col3">교육시간</th>
		  <th class = "col4">비고</th>
        </tr>
        <th class = "col1">기대효과</th>
	  <td colspan= "6"><%= f.text_area :expectation %></td>
        </tr>
      </tbody>
    </table>
    <p>
	<%= f.submit %>
    <p>
  </body>
</html>
<% end %>

app/views/education/_banner.html.erb
<span>Educations</span>

app/views/education/_sidemenu.html.erb
<p> Course List </p>
<ul>
<% @courses.each do |course| %>
  <li><%= link_to course.title, course_path(course) %></li>
<% end %>
</ul>

app/views/education/index.html.erb
<h1>Education#index</h1>
<p>Find me in app/views/education/index.html.erb</p>

app/views/education/new.html.erb
<%= form_for :course, url: courses_path do |f| %>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <title>Course description</title>
    <style>
      table {
        width: 800px;
		height: 500px;
      }
      table{
        border-style: solid;
		border-width: 2px;
		border-collapse: collapse;
      }
	  th, td{
        border-style: solid;
		border-width: 1px;
      }
	  th{
		background-color: gray;
	  }
	  th.col1{
		width: 100px;
	  }
	  th.col2, td.col2{
		width: 150px;
	  }
	  th.col3, td.col3{
		width: 40px;
	  }
	  th.col4, td.col4{
		width: 60px;
	  }
	  
    </style>
  </head>
  <body>
    <table>
      <thead>
        <tr>
          <th class = "col1">과목명</th>
          <th colspan= "6"><%= f.text_field:title %></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th class = "col1">과정목표</th>
          <td  colspan= "6"><%= f.text_area:purpose %></td>
          <!-- <td rowspan="2">Dolor</td> -->
        </tr>
        <tr>
          <th class = "col1">과목특징</th>
          <td  colspan= "6"><%= f.text_area:feature %></td>
        </tr>
        <tr>
          <th rowspan="2", class = "col1">과정개요</th>
          <th class = "col2">교육인원</th>
          <td><%= f.number_field :overview_number_of_memeber, in: 1..100, step: 1 %></td>
          <th class = "col2">교육형태</th>
	  <td colspan= "2"><%= f.text_field :overview_type %></td>
        </tr>
		<tr>
          <th class = "col2">교육대상</th>
          <td><%= f.text_area :overview_target %></td>
          <th class = "col2">교육시간</th>
	  <td colspan= "2"><%= f.number_filed :overview_time%></td>
        </tr>
	<tr>
	  <th>프로그램</th>
          <th class = "col2">LO</th>
          <th colspan= "2">교육내용</th>
          <th class = "col3">교육시간</th>
		  <th class = "col4">비고</th>
        </tr>
        <th class = "col1">기대효과</th>
	  <td colspan= "6"><%= f.text_area :expectation %></td>
        </tr>
      </tbody>
    </table>
  </body>
</html>
<% end %>

app/views/home/_banner.html.erb
<span>All of Software in your business</span>

app/views/tools/_sidemenu.html.erb
...

app/views/tools/index.html.erb
<h1>Tools#index</h1>
<p>Find me in app/views/tools/index.html.erb</p>