config/routes.rb
Juconsulting::Application.routes.draw do
  resources :consults

  get "tools/index"
  get "education/index"
  root "home#index"
  get "company/index"
  get "company/intro"
  get "company/partner"
  get "about_us/index"
  get "about_us/choisw"
  get "about_us/kimjh"
  get "about_us/organization"
  get "about_us/consultant"
  get "about_us/perf"
  get "home/index"
  get "courses/manager_index"
  get "courses/manager_show"
  get "consulting/manager_index"
  get "consults/manager_index"

  resources :courses do
    resource :course_programs
  end

  resources :consulting

end

app/models/consult.rb
class Consult < ActiveRecord::Base
end

app/models/consulting.rb
class Consulting < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :course_programs, dependent: :destroy
end

app/models/course_program.rb
class CourseProgram < ActiveRecord::Base
	belongs_to :course
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index
  end

  def choisw
  end

  def kimjh
  end

  def organization
  end

  def consultant
  end

  def perf
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  def index
  end
  def intro
  end
  def perf
  end
  def partner
  end
end

app/controllers/consulting_controller.rb
class ConsultingController < ApplicationController
  before_action :call_consulting

  def call_consulting
    @consultings = Consulting.all
  end

  def index
  end

  def new
	@consulting = Consulting.new
  end
  def create
	@consulting = Consulting.new(consulting_params)
	if @consulting.save
		redirect_to controller: "consultings", action:"manager_index"
	else
		render 'new'
	end
  end
  def manager_index
	@consultings = Consulting.all
  end

  def show
    @consulting = Consulting.find(params[:id])
  end
  private
	def consulting_params
		params.require(:consulting).permit(:title, :banner_txt, :desc, :features, :main_img, :etc_img)
	end
end

app/controllers/consults_controller.rb
class ConsultsController < ApplicationController
  before_action :set_consult, only: [:show, :edit, :update, :destroy]

  # GET /consults
  # GET /consults.json
  def index
    @consults = Consult.all
  end

  # GET /consults/1
  # GET /consults/1.json
  def show
    @consults = Consult.all
  end

  # GET /consults/new
  def new
    @consult = Consult.new
  end

  # GET /consults/1/edit
  def edit
  end

  # POST /consults
  # POST /consults.json
  def create
    @consult = Consult.new(consult_params)

    respond_to do |format|
      if @consult.save
        format.html { redirect_to @consult, notice: 'Consult was successfully created.' }
        format.json { render action: 'show', status: :created, location: @consult }
      else
        format.html { render action: 'new' }
        format.json { render json: @consult.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consults/1
  # PATCH/PUT /consults/1.json
  def update
    respond_to do |format|
      if @consult.update(consult_params)
        format.html { redirect_to @consult, notice: 'Consult was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @consult.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consults/1
  # DELETE /consults/1.json
  def destroy
    @consult.destroy
    respond_to do |format|
      format.html { redirect_to consults_url }
      format.json { head :no_content }
    end
  end

  def manager_index
	render 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consult
      @consult = Consult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consult_params
      params[:consult]
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
	@courses = Course.all
  end
  def manager_index
	@courses = Course.all
  end
  def edit
	@course = Course.find(params[:id])
  end
  def update
	@course = Course.find(params[:id])
	if @course.update(course_params)
		redirect_to @course
	else
		render 'edit'
	end
  end

  def show
	@courses = Course.all
	@course = Course.find(params[:id])
  end
  def manager_show
	@course = Course.find(params[:id])
  end
  def new
	@course = Course.new
  end
  def create
	@course = Course.new(course_params)
	if @course.save
		redirect_to controller: "courses", action:"manager_show", id: @course.id
	else
		render 'new'
	end
  end

  def destroy
	@course = Course.find(params[:id])
	@course.destroy

	redirect_to controller: "courses", action:"manager_index"
  end

  private
	def course_params
		params.require(:course).permit(:title, :purpose, :feature, :overview_number_of_memeber, :overview_type, :overview_target, :overview_time, :expectation)
	end
end

app/controllers/education_controller.rb
class EducationController < ApplicationController
  def index
	@courses = Course.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/consulting_helper.rb
module ConsultingHelper
end

app/helpers/consults_helper.rb
module ConsultsHelper
end

app/helpers/course_programs_helper.rb
module CourseProgramsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/education_helper.rb
module EducationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/consulting/_banner.html.erb
<span>Consulting</span>

app/views/consulting/_sidemenu.html.erb
<ul class="global-child">
	<% Consulting.all.each do |consulting| %>
	<li><%= link_to consulting.title, consulting %></li>
	<% end %>
</ul>

app/views/consulting/index.html.erb
<h1>Consulting#index</h1>
<p>Find me in app/views/consulting/index.html.erb</p>

app/views/consulting/manager_index.html.erb
<h1>Consulting Manager</h1>

<p><%= link_to 'Regist Consult', new_consulting_path %></p>
<p> Consulting List </p>
<table>
 <% @consultings.each do |consulting| %>
      <tr>
        <td><%= consulting.title %></td>
        <td><%= link_to 'Edit', edit_consulting_path(consulting) %></td>
        <td><%= link_to 'Destroy', consulting_path(consulting),
				method: :delete,
				data: {confirm: 'Are you sure?' }  %></td>
      </tr>
 <% end %>
</table>

app/views/consulting/new.html.erb
<%= form_for :consulting, consulting_path  do |f| %>
<h1>title: <%= f.text_area :title %></h1>
<p>banner_txt: <%= f.text_area :banner_txt %></p>
<p>main_img: <%= f.text_area :main_img %></p>
<p>desc: <%= f.text_area :desc %></p>
<h2>Service Features</h2>
<span>features: <%= f.text_area :features %></span>

<p>etc_img: <%= f.text_area :etc_img %></p>
<%= f.submit %>
<% end %>

app/views/consulting/show.html.erb
<section class="consultant">
  <h1><%= @consulting.title %></h1>
  <p><%= @consulting.banner_txt %></p>
  <p><%= image_tag @consulting.main_img %></p>
  <p><%= @consulting.desc %></p>
  <h2>Service Features</h2>
  <span><%= raw(@consulting.features) %></span>
  <p><%= image_tag @consulting.etc_img %></p>
</section>

app/views/consults/_banner.html.erb
<span>Consulting</span>

app/views/consults/_form.html.erb
<%= form_for(@consult) do |f| %>
  <% if @consult.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consult.errors.count, "error") %> prohibited this consult from being saved:</h2>

      <ul>
      <% @consult.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
   <% end %>
	<h1>Consulting Information</h1>
	<p>title: <%= f.text_area :title %></p>
	<p>banner_txt: <%= f.text_area :banner_txt %></p>
	<p>main_img: <%= f.text_area :main_img %></p>
	<p>desc: <%= f.text_area :desc %></p>
	<h1>Service Features</h2>
	<p>features: <%= f.text_area :features %></p>
	<p>etc_img: <%= f.text_area :etc_img %></p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/consults/_sidemenu.html.erb
<ul class="global-child">
	<% Consult.all.each do |consult| %>
	<li><%= link_to consult.title, consult %></li>
	<% end %>
</ul>

app/views/consults/edit.html.erb
<h1>Editing consult</h1>

<%= render 'form' %>

<%= link_to 'Show', @consult %> |
<%= link_to 'Back', consults_path %>

app/views/consults/index.html.erb
<h1>Listing consults</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @consults.each do |consult| %>
      <tr>
	<td><%= consult.title %> </td>
        <td><%= link_to 'Show', consult %></td>
        <td><%= link_to 'Edit', edit_consult_path(consult) %></td>
        <td><%= link_to 'Destroy', consult, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Consult', new_consult_path %>

app/views/consults/manager_index.html.erb
<p> tttt </p>

app/views/consults/new.html.erb
<h1>New consult</h1>

<%= render 'form' %>

<%= link_to 'Back', consults_path %>

app/views/consults/show.html.erb
<section class="consultant">
  <h1><%= @consult.title %></h1>
  <p><%= @consult.banner_txt %></p>
  <p><%= image_tag @consult.main_img %></p>
  <p><%= @consult.desc %></p>
  <h2>Service Features</h2>
  <span><%= raw(@consult.features) %></span>
  <p><%= image_tag @consult.etc_img %></p>
</section>