config/routes.rb
Juconsulting::Application.routes.draw do
  resources :consults

  get "tools/index"
  get "education/index"
  root "home#index"
  get "company/index"
  get "company/intro"
  get "company/partner"
  get "about_us/index"
  get "about_us/choisw"
  get "about_us/kimjh"
  get "about_us/organization"
  get "about_us/consultant"
  get "about_us/perf"
  get "home/index"
  get "courses/manager_index"
  get "courses/manager_show"
  get "consulting/manager_index"
  get "consults/manager_index"

  resources :courses do
    resource :course_programs
  end

  resources :consulting

end

app/models/consult.rb
class Consult < ActiveRecord::Base
end

app/models/consulting.rb
class Consulting < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :course_programs, dependent: :destroy
end

app/models/course_program.rb
class CourseProgram < ActiveRecord::Base
	belongs_to :course
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index
  end

  def choisw
  end

  def kimjh
  end

  def organization
  end

  def consultant
  end

  def perf
  end
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  def index
  end
  def intro
  end
  def perf
  end
  def partner
  end
end

app/controllers/consults_controller.rb
class ConsultsController < ApplicationController
  before_action :set_consult, only: [:show, :edit, :update, :destroy]

  # GET /consults
  # GET /consults.json
  def index
    @consults = Consult.all
  end

  # GET /consults/1
  # GET /consults/1.json
  def show
    @consults = Consult.all
  end

  # GET /consults/new
  def new
    @consult = Consult.new
  end

  # GET /consults/1/edit
  def edit
  end

  # POST /consults
  # POST /consults.json
  def create
    @consult = Consult.new(consult_params)

    respond_to do |format|
      if @consult.save
        format.html { redirect_to @consult, notice: 'Consult was successfully created.' }
        format.json { render action: 'show', status: :created, location: @consult }
      else
        format.html { render action: 'new' }
        format.json { render json: @consult.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consults/1
  # PATCH/PUT /consults/1.json
  def update
    respond_to do |format|
      if @consult.update(consult_params)
        format.html { redirect_to @consult, notice: 'Consult was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @consult.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consults/1
  # DELETE /consults/1.json
  def destroy
    @consult.destroy
    respond_to do |format|
      format.html { redirect_to consults_url }
      format.json { head :no_content }
    end
  end

  def manager_index
	render 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consult
      @consult = Consult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consult_params
      params[:consult]
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
	@courses = Course.all
  end
  def manager_index
	@courses = Course.all
  end
  def edit
	@course = Course.find(params[:id])
  end
  def update
	@course = Course.find(params[:id])
	if @course.update(course_params)
		redirect_to @course
	else
		render 'edit'
	end
  end

  def show
	@courses = Course.all
	@course = Course.find(params[:id])
  end
  def manager_show
	@course = Course.find(params[:id])
  end
  def new
	@course = Course.new
  end
  def create
	@course = Course.new(course_params)
	if @course.save
		redirect_to controller: "courses", action:"manager_show", id: @course.id
	else
		render 'new'
	end
  end

  def destroy
	@course = Course.find(params[:id])
	@course.destroy

	redirect_to controller: "courses", action:"manager_index"
  end

  private
	def course_params
		params.require(:course).permit(:title, :purpose, :feature, :overview_number_of_memeber, :overview_type, :overview_target, :overview_time, :expectation)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/consulting_helper.rb
module ConsultingHelper
end

app/helpers/consults_helper.rb
module ConsultsHelper
end

app/helpers/course_programs_helper.rb
module CourseProgramsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/education_helper.rb
module EducationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Juconsulting</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="whole_frame">
    <header>
      <div id="title_nav">
        <%= link_to image_tag('company_logo.png', size: "280x80"), root_path, :class => "banner_link" %>
        <nav class="global">
          <ul class="global-parent">
            <li class="global-parent">
              <%= link_to "ABOUT US", "#", :class => "gnav_link" %>
              <%= render 'about_us/sidemenu' %>
            </li>
            <li class="global-parent">
              <%= link_to "CONSULTING", "#", :class => "gnav_link" %>
              <%= render 'consults/sidemenu' %>
            </li>
            <li class="global-parent">
              <%= link_to "EDUCATION", "#", :class => "gnav_link" %>
              <%= render 'courses/sidemenu' %>
            </li>
            <li class="global-parent"><%= link_to "TOOLS", tools_index_path, :class => "gnav_link" %></li>
          </ul>
          <br class="clearfix" />
        </nav>
      </div>
    </header>
    <section id="body_frame">
      <main class="nosidemenu">
        <%= yield %>
      </main>
      <br class="clearfix" />
    </section>

    <!--nav class="footer_nav">
      Footer Navigation
    </nav-->
    <!--footer>
      사업자 정보 / 공개채용 / FAQ<br />
      사업자번호: 000-000000-000
    </footer-->
  </div>
</body>
</html>

app/views/layouts/globalnav.html.erb
<nav class="global">
	<%= link_to "About Us", about_us_index_path, :class => "gnav_link" %> /
	<%= link_to "Company", company_index_path, :class => "gnav_link" %> /
	<%= link_to "Consulting", consulting_index_path, :class => "gnav_link" %> /
	<%= link_to "Education", education_index_path, :class => "gnav_link" %> /
	<%= link_to "Tools", tools_index_path, :class => "gnav_link" %>
</nav>